=== tdiesler/nessus-didcomm/agent/src/test/resources/w3c/schemas/UniversityDegree.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "@context" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "credentialSchema" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "credentialSubject" : {
      "type" : "object",
      "properties" : {
        "degree" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string"
            },
            "type" : {
              "type" : "string"
            }
          },
          "additionalProperties" : false
        },
        "id" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "expirationDate" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "issuanceDate" : {
      "type" : "string"
    },
    "issued" : {
      "type" : "string"
    },
    "issuer" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "proof" : {
      "type" : "object",
      "properties" : {
        "created" : {
          "type" : "string"
        },
        "creator" : {
          "type" : "string"
        },
        "domain" : {
          "type" : "string"
        },
        "jws" : {
          "type" : "string"
        },
        "nonce" : {
          "type" : "string"
        },
        "proofPurpose" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string"
        },
        "verificationMethod" : {
          "type" : "string"
        }
      },
      "additionalProperties" : false
    },
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "validFrom" : {
      "type" : "string"
    }
  },
  "required" : [ "@context", "type" ],
  "additionalProperties" : false
}

=== tdiesler/nessus-didcomm/agent/src/test/resources/w3c/serialized/UniversityDegree.json
{
  "@context": ["https://www.w3.org/2018/credentials/v1", "https://www.w3.org/2018/credentials/examples/v1"],
  "credentialSubject": {
    "degree": {
      "name": "Bachelor of Science and Arts",
      "type": "BachelorDegree"
    },
    "id": "did:example:123"
  },
  "id": "http://example.gov/credentials/3732",
  "issued": "2020-03-10T04:24:12.164Z",
  "issuer": {
    "id": "did:example:456"
  },
  "type": ["VerifiableCredential", "UniversityDegreeCredential"]
}
