=== tdiesler/nessus-didcomm/agent/src/main/resources/nessus/schema/BirthCertificateSchema-draft-01.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/BirthCertificate",
    "definitions": {
        "BirthCertificate": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "givenName": {
                    "type": "string"
                },
                "familyName": {
                    "type": "string"
                },
                "citizenship": {
                    "type": "string"
                },
                "birthDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "birthPlace": {
                    "$ref": "#/definitions/BirthPlace"
                },
                "parent": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Parent"
                    }
                }
            },
            "required": [
                "birthDate",
                "birthPlace",
                "citizenship",
                "familyName",
                "givenName",
                "id",
                "parent",
                "type"
            ],
            "title": "BirthCertificate"
        },
        "BirthPlace": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string"
                },
                "address": {
                    "$ref": "#/definitions/Address"
                }
            },
            "required": [
                "address",
                "type"
            ],
            "title": "BirthPlace"
        },
        "Address": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string"
                },
                "addressLocality": {
                    "type": "string"
                },
                "addressRegion": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string",
                    "format": "integer"
                },
                "streetAddress": {
                    "type": "string"
                }
            },
            "required": [
                "addressLocality",
                "addressRegion",
                "postalCode",
                "streetAddress",
                "type"
            ],
            "title": "Address"
        },
        "Parent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "givenName": {
                    "type": "string"
                },
                "familyName": {
                    "type": "string"
                },
                "maidenName": {
                    "type": "string"
                }
            },
            "required": [
                "familyName",
                "givenName",
                "id",
                "type"
            ],
            "title": "Parent"
        }
    }
}

=== tdiesler/nessus-didcomm/agent/src/test/resources/schema/birth-certificate.json
{
  "id": "did:example:8vFBbPrhBUyG6DEzVncBZpzBNsmRrbfsQKXQKPLskBCu",
  "type": "Person",
  "givenName": "Anand",
  "familyName": "Hamal",
  "citizenship": "US",
  "birthDate": "2017-10-01T00:00:00Z",
  "birthPlace": {
    "type": "Hospital",
    "address": {
      "type": "US address",
      "addressLocality": "Denver",
      "addressRegion": "CO",
      "postalCode": "80209",
      "streetAddress": "123 Main St."
    }
  },
  "parent": [{
    "id": "did:example:BcRisGnqV4QPb6bRmDCqEjyuubBarS1Y1nhDwxBMTXY4",
    "type": "Person",
    "givenName": "Malathi",
    "familyName": "Hamal",
    "maidenName": "Holla"
  }, {
    "id": "did:example:BgXRjB4RPrrsUVoVNaYNwzfznKsWep7AWrZkiyVcorEN",
    "type": "Person",
    "givenName": "Rajesh",
    "familyName": "Hamal"
  }]
}
