=== tdiesler/nessus-didcomm/agent/src/main/resources/nessus/schema/BirthCertificateSchema-draft-1.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "title": "Basic Passport for a natural person",

    "type": "object",
    "properties": {
        "@context": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "credentialSchema": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "credentialStatus": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "credentialSubject": { "$ref": "#/definitions/BirthCertificate" },
        "evidence": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "documentPresence": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "evidenceDocument": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "id": {
                        "type": "string"
                    },
                    "subjectPresence": {
                        "type": "string"
                    },
                    "type": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "verifier": {
                        "type": "string"
                    }
                },
                "additionalProperties": false
            }
        },
        "expirationDate": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "issuanceDate": {
            "type": "string"
        },
        "issued": {
            "type": "string"
        },
        "issuer": {
            "type": "string"
        },
        "proof": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "jws": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "proofPurpose": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "verificationMethod": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "type": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "validFrom": {
            "type": "string"
        }
    },
    "required": [
        "@context",
        "type"
    ],
    "additionalProperties": false,

    "definitions": {
        "BirthCertificate": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "givenName": {
                    "type": "string"
                },
                "familyName": {
                    "type": "string"
                },
                "birthDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "birthPlace": {
                    "$ref": "#/definitions/BirthPlace"
                },
                "citizenship": {
                    "type": "string"
                },
                "parent": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Parent"
                    }
                }
            },
            "required": [
                "id",
                "birthDate",
                "birthPlace",
                "citizenship",
                "familyName",
                "givenName",
                "parent"
            ],
            "title": "BirthCertificate"
        },
        "BirthPlace": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string"
                },
                "address": {
                    "$ref": "#/definitions/Address"
                }
            },
            "required": [
                "address",
                "type"
            ],
            "title": "BirthPlace"
        },
        "Address": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string"
                },
                "addressLocality": {
                    "type": "string"
                },
                "addressRegion": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string",
                    "format": "integer"
                },
                "streetAddress": {
                    "type": "string"
                }
            },
            "required": [
                "addressLocality",
                "addressRegion",
                "postalCode",
                "streetAddress",
                "type"
            ],
            "title": "Address"
        },
        "Parent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "givenName": {
                    "type": "string"
                },
                "familyName": {
                    "type": "string"
                },
                "maidenName": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "givenName",
                "familyName"
            ],
            "title": "Parent"
        }
    }
}

=== tdiesler/nessus-didcomm/agent/src/main/resources/nessus/vc-templates/BirthCertificate.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1"
  ],
  "type": [
    "VerifiableCredential",
    "BirthCertificate"
  ],
  "credentialSchema": {
    "id": "class:/nessus/schema/BirthCertificateSchema-draft-1.json",
    "type": "JsonSchemaValidator2018"
  },
  "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
  "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
  "issuanceDate": "2021-08-31T00:00:00Z",
  "credentialSubject": {
    "id": "did:example:8vFBbPrhBUyG6DEzVncBZpzBNsmRrbfsQKXQKPLskBCu",
    "type": "Person",
    "givenName": "Anand",
    "familyName": "Hamal",
    "citizenship": "US",
    "birthDate": "2017-10-01T00:00:00Z",
    "birthPlace": {
      "type": "Hospital",
      "address": {
        "type": "US address",
        "addressLocality": "Denver",
        "addressRegion": "CO",
        "postalCode": "80209",
        "streetAddress": "123 Main St."
      }
    },
    "parent": [{
      "id": "did:example:BcRisGnqV4QPb6bRmDCqEjyuubBarS1Y1nhDwxBMTXY4",
      "type": "Person",
      "givenName": "Malathi",
      "familyName": "Hamal",
      "maidenName": "Holla"
    }, {
      "id": "did:example:BgXRjB4RPrrsUVoVNaYNwzfznKsWep7AWrZkiyVcorEN",
      "type": "Person",
      "givenName": "Rajesh",
      "familyName": "Hamal"
    }]
  }
}
