=== tdiesler/nessus-didcomm/agent/src/main/resources/nessus/schema/PassportSchema-draft-1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "title": "Basic Passport for a natural person",

  "type": "object",
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "credentialSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "credentialStatus": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "credentialSubject": { "$ref": "#/definitions/Passport" },
    "evidence": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "documentPresence": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "evidenceDocument": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "id": {
            "type": "string"
          },
          "subjectPresence": {
            "type": "string"
          },
          "type": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "verifier": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "expirationDate": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "issuanceDate": {
      "type": "string"
    },
    "issued": {
      "type": "string"
    },
    "issuer": {
      "type": "string"
    },
    "proof": {
      "type": "object",
      "properties": {
        "created": {
          "type": "string"
        },
        "creator": {
          "type": "string"
        },
        "domain": {
          "type": "string"
        },
        "jws": {
          "type": "string"
        },
        "nonce": {
          "type": "string"
        },
        "proofPurpose": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "verificationMethod": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "validFrom": {
      "type": "string"
    }
  },
  "required": [
    "@context",
    "type"
  ],
  "additionalProperties": false,

  "definitions": {
    "Passport": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "givenName": {
          "type": "string",
          "minLength": 3
        },
        "familyName": {
          "type": "string",
          "minLength": 3
        },
        "citizenship": {
          "type": "string",
          "minLength": 2
        }
      },
      "required": [
        "id",
        "givenName",
        "familyName",
        "citizenship"
      ],
      "additionalProperties": false
    }
  }
}

=== tdiesler/nessus-didcomm/agent/src/test/resources/vc/passport.vc.json
{
  "type" : [ "VerifiableCredential", "Passport" ],
  "@context" : [ "https://www.w3.org/2018/credentials/v1", "https://w3id.org/security/suites/jws-2020/v1" ],
  "id" : "urn:uuid:cf08da0c-b4fd-446e-83be-3242a56a201b",
  "issuer" : "did:peer:2.Ez6LSkzu2EgTZGbo6ZWrcctw2wfDjxXa1tAHWPjw7ae4TJFdN.Vz6MkiXm1PLo9DFwNx1ADcEVSyctXFt9YtR9HtCqVNsnVVKvj.SeyJ0IjoiZG0iLCJzIjoiaHR0cDovLzE5Mi4xNjguMC4xMDo5MDAwIn0",
  "issuanceDate" : "2023-06-29T05:39:45.075445Z",
  "credentialSchema" : {
    "id" : "class:nessus/schema/PassportSchema-draft-01.json",
    "type" : "JsonSchemaValidator2018"
  },
  "credentialSubject" : {
    "id" : "did:peer:2.Ez6LShGAZLttG3b5NLFx9b1Dk9RdV2Exn4t5cJF3ZkASU8MGZ.Vz6Mkt3DCpY8HnGjeAD7hw1yX9QCLNfyjvW1XSdsT9amE9gtE.SeyJ0IjoiZG0iLCJzIjoiaHR0cDovLzE5Mi4xNjguMC4xMDo5MDAwIn0",
    "givenName" : "Malathi",
    "familyName" : "Hamal",
    "citizenship" : "US"
  },
  "proof" : {
    "type" : "JsonWebSignature2020",
    "creator" : "did:peer:2.Ez6LSkzu2EgTZGbo6ZWrcctw2wfDjxXa1tAHWPjw7ae4TJFdN.Vz6MkiXm1PLo9DFwNx1ADcEVSyctXFt9YtR9HtCqVNsnVVKvj.SeyJ0IjoiZG0iLCJzIjoiaHR0cDovLzE5Mi4xNjguMC4xMDo5MDAwIn0",
    "created" : "2023-06-29T05:39:45Z",
    "proofPurpose" : "assertionMethod",
    "verificationMethod" : "did:peer:2.Ez6LSkzu2EgTZGbo6ZWrcctw2wfDjxXa1tAHWPjw7ae4TJFdN.Vz6MkiXm1PLo9DFwNx1ADcEVSyctXFt9YtR9HtCqVNsnVVKvj.SeyJ0IjoiZG0iLCJzIjoiaHR0cDovLzE5Mi4xNjguMC4xMDo5MDAwIn0",
    "jws" : "eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFZERTQSJ9..bebiqzKtukKc9_hxxNyZEBeosytsEEcX5XPU1J5SRZPUAQgtImYqOS9z0x5rayeWQfYNqbZ7QXWxZ0arQN8GBg"
  }
}
