=== tdiesler/nessus-didcomm/agent/src/main/resources/nessus/schema/UniversityTranscriptSchema-draft-01.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Basic Passport for a natural person",
    "type": "object",
    "properties": {
        "@context": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "credentialSchema": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "credentialStatus": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "credentialSubject": { "$ref": "#/definitions/UniversityTranscript" },
        "evidence": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "documentPresence": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "evidenceDocument": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "id": {
                        "type": "string"
                    },
                    "subjectPresence": {
                        "type": "string"
                    },
                    "type": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "verifier": {
                        "type": "string"
                    }
                },
                "additionalProperties": false
            }
        },
        "expirationDate": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "issuanceDate": {
            "type": "string"
        },
        "issued": {
            "type": "string"
        },
        "issuer": {
            "type": "string"
        },
        "proof": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "jws": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "proofPurpose": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "verificationMethod": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "type": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "validFrom": {
            "type": "string"
        }
    },
    "required": [
        "@context",
        "type"
    ],
    "additionalProperties": false,

    "definitions": {
        "UniversityTranscript": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "givenName": {
                    "type": "string"
                },
                "familyName": {
                    "type": "string"
                },
                "ssn": {
                    "type": "string"
                },
                "degree": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "year": {
                    "type": "string",
                    "format": "integer"
                },
                "average": {
                    "type": "string",
                    "format": "integer"
                }
            },
            "required": [
                "average",
                "degree",
                "familyName",
                "givenName",
                "id",
                "ssn",
                "status",
                "year"
            ],
            "title": "UniversityTranscript"
        }
    }
}

=== tdiesler/nessus-didcomm/agent/src/main/resources/nessus/vc-templates/UniversityTranscript.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1"
  ],
  "type": [
    "VerifiableCredential",
    "UniversityTranscript"
  ],
  "credentialSchema": {
    "id": "class:nessus/schema/UniversityTranscriptSchema-draft-01.json",
    "type": "JsonSchemaValidator2018"
  },
  "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
  "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
  "issuanceDate": "2021-08-31T00:00:00Z",
  "expirationDate": "2031-08-31T00:00:00Z",
  "credentialSubject": {
    "id": "did:example:BcRisGnqV4QPb6bRmDCqEjyuubBarS1Y1nhDwxBMTXY4",
    "givenName": "Alice",
    "familyName": "Garcia",
    "ssn": "123-45-6789",
    "degree": "Bachelor of Science, Marketing",
    "status": "graduated",
    "year": "2015",
    "average": "5"
  }
}
